import handleResettingPlayerStatesBeforeNewHand from './handleResettingPlayerStatesBeforeNewHand'

test('Returns correctly resetted player array', () => {
  // Only resets isAllIn at the moment.
  expect(
    handleResettingPlayerStatesBeforeNewHand([
      {
        index: 0,
        holeCards: [],
        hand: [],
        hasActed: true,
        name: 'Viktor Selbst',
        chips: 0,
        chipsCurrentlyInvested: 0,
        id: '8a8405dc-3f9e-4068-b4df-3d6671ef19a9',
        hasFolded: false,
        isAllIn: true,
      },
      {
        index: 1,
        holeCards: [],
        hand: [],
        hasActed: true,
        name: 'Liv Hellmuth',
        chips: 1500,
        chipsCurrentlyInvested: 0,
        id: 'aa654ab0-4a83-4c00-90f4-4bf4a067a02f',
        hasFolded: true,
        isAllIn: false,
      },
      {
        index: 2,
        holeCards: [],
        hand: [],
        hasActed: true,
        name: 'JC Tran',
        chips: 1500,
        chipsCurrentlyInvested: 0,
        id: '4509a8a1-4c7f-4cd7-bada-8c8e93b269ba',
        hasFolded: true,
        isAllIn: false,
      },
      {
        index: 3,
        holeCards: [],
        hand: [],
        hasActed: true,
        name: 'Scott Ivey',
        chips: 3030,
        chipsCurrentlyInvested: 0,
        id: 'f5830abf-4372-4763-8fd8-e3c67d16de91',
        hasFolded: false,
        isAllIn: true,
      },
      {
        index: 4,
        holeCards: [],
        hand: [],
        hasActed: true,
        name: 'Liv Tran',
        chips: 1490,
        chipsCurrentlyInvested: 0,
        id: '33333c18-9214-4b10-ae55-f4318ffb1be1',
        hasFolded: true,
        isAllIn: false,
      },
      {
        index: 5,
        holeCards: [],
        hand: [],
        hasActed: true,
        name: 'Liv Tran',
        chips: 1480,
        chipsCurrentlyInvested: 0,
        id: 'ebc4e7c2-0081-460a-a173-bd00e07905e2',
        hasFolded: true,
        isAllIn: false,
      },
    ]),
  ).toEqual([
    {
      index: 0,
      holeCards: [],
      hand: [],
      hasActed: false,
      name: 'Viktor Selbst',
      chips: 0,
      chipsCurrentlyInvested: 0,
      id: '8a8405dc-3f9e-4068-b4df-3d6671ef19a9',
      hasFolded: false,
      isAllIn: false,
    },
    {
      index: 1,
      holeCards: [],
      hand: [],
      hasActed: false,
      name: 'Liv Hellmuth',
      chips: 1500,
      chipsCurrentlyInvested: 0,
      id: 'aa654ab0-4a83-4c00-90f4-4bf4a067a02f',
      hasFolded: true,
      isAllIn: false,
    },
    {
      index: 2,
      holeCards: [],
      hand: [],
      hasActed: false,
      name: 'JC Tran',
      chips: 1500,
      chipsCurrentlyInvested: 0,
      id: '4509a8a1-4c7f-4cd7-bada-8c8e93b269ba',
      hasFolded: true,
      isAllIn: false,
    },
    {
      index: 3,
      holeCards: [],
      hand: [],
      hasActed: false,
      name: 'Scott Ivey',
      chips: 3030,
      chipsCurrentlyInvested: 0,
      id: 'f5830abf-4372-4763-8fd8-e3c67d16de91',
      hasFolded: false,
      isAllIn: false,
    },
    {
      index: 4,
      holeCards: [],
      hand: [],
      hasActed: false,
      name: 'Liv Tran',
      chips: 1490,
      chipsCurrentlyInvested: 0,
      id: '33333c18-9214-4b10-ae55-f4318ffb1be1',
      hasFolded: true,
      isAllIn: false,
    },
    {
      index: 5,
      holeCards: [],
      hand: [],
      hasActed: false,
      name: 'Liv Tran',
      chips: 1480,
      chipsCurrentlyInvested: 0,
      id: 'ebc4e7c2-0081-460a-a173-bd00e07905e2',
      hasFolded: true,
      isAllIn: false,
    },
  ])
})
