// Todo: Not sure how to test randomness
import reducer, { DEAL_CARDS_TO_PLAYERS } from '../gameManager'

test('reducers', () => {
  let state
  state = reducer(
    {
      pot: 0,
      deck: [
        { rank: { value: 7, symbol: '7' }, suit: { symbol: '♦', letter: 'd', color: 'red' } },
        { rank: { value: 9, symbol: '9' }, suit: { symbol: '♦', letter: 'd', color: 'red' } },
        { rank: { value: 10, symbol: 'T' }, suit: { symbol: '♣', letter: 'c', color: 'black' } },
        { rank: { value: 14, symbol: 'A' }, suit: { symbol: '♠', letter: 's', color: 'black' } },
        { rank: { value: 12, symbol: 'Q' }, suit: { symbol: '♥', letter: 'h', color: 'red' } },
        { rank: { value: 5, symbol: '5' }, suit: { symbol: '♠', letter: 's', color: 'black' } },
        { rank: { value: 3, symbol: '3' }, suit: { symbol: '♣', letter: 'c', color: 'black' } },
        { rank: { value: 2, symbol: '2' }, suit: { symbol: '♥', letter: 'h', color: 'red' } },
        { rank: { value: 14, symbol: 'A' }, suit: { symbol: '♣', letter: 'c', color: 'black' } },
        { rank: { value: 2, symbol: '2' }, suit: { symbol: '♦', letter: 'd', color: 'red' } },
        { rank: { value: 6, symbol: '6' }, suit: { symbol: '♣', letter: 'c', color: 'black' } },
        { rank: { value: 9, symbol: '9' }, suit: { symbol: '♥', letter: 'h', color: 'red' } },
        { rank: { value: 7, symbol: '7' }, suit: { symbol: '♠', letter: 's', color: 'black' } },
        { rank: { value: 4, symbol: '4' }, suit: { symbol: '♥', letter: 'h', color: 'red' } },
        { rank: { value: 8, symbol: '8' }, suit: { symbol: '♠', letter: 's', color: 'black' } },
        { rank: { value: 9, symbol: '9' }, suit: { symbol: '♠', letter: 's', color: 'black' } },
        { rank: { value: 13, symbol: 'K' }, suit: { symbol: '♥', letter: 'h', color: 'red' } },
        { rank: { value: 6, symbol: '6' }, suit: { symbol: '♠', letter: 's', color: 'black' } },
        { rank: { value: 5, symbol: '5' }, suit: { symbol: '♣', letter: 'c', color: 'black' } },
        { rank: { value: 13, symbol: 'K' }, suit: { symbol: '♦', letter: 'd', color: 'red' } },
        { rank: { value: 7, symbol: '7' }, suit: { symbol: '♣', letter: 'c', color: 'black' } },
        { rank: { value: 13, symbol: 'K' }, suit: { symbol: '♠', letter: 's', color: 'black' } },
        { rank: { value: 3, symbol: '3' }, suit: { symbol: '♦', letter: 'd', color: 'red' } },
        { rank: { value: 5, symbol: '5' }, suit: { symbol: '♥', letter: 'h', color: 'red' } },
        { rank: { value: 11, symbol: 'J' }, suit: { symbol: '♦', letter: 'd', color: 'red' } },
        { rank: { value: 4, symbol: '4' }, suit: { symbol: '♠', letter: 's', color: 'black' } },
        { rank: { value: 9, symbol: '9' }, suit: { symbol: '♣', letter: 'c', color: 'black' } },
        { rank: { value: 8, symbol: '8' }, suit: { symbol: '♣', letter: 'c', color: 'black' } },
        { rank: { value: 6, symbol: '6' }, suit: { symbol: '♦', letter: 'd', color: 'red' } },
        { rank: { value: 12, symbol: 'Q' }, suit: { symbol: '♠', letter: 's', color: 'black' } },
        { rank: { value: 2, symbol: '2' }, suit: { symbol: '♣', letter: 'c', color: 'black' } },
        { rank: { value: 3, symbol: '3' }, suit: { symbol: '♥', letter: 'h', color: 'red' } },
        { rank: { value: 6, symbol: '6' }, suit: { symbol: '♥', letter: 'h', color: 'red' } },
        { rank: { value: 2, symbol: '2' }, suit: { symbol: '♠', letter: 's', color: 'black' } },
        { rank: { value: 13, symbol: 'K' }, suit: { symbol: '♣', letter: 'c', color: 'black' } },
        { rank: { value: 7, symbol: '7' }, suit: { symbol: '♥', letter: 'h', color: 'red' } },
        { rank: { value: 14, symbol: 'A' }, suit: { symbol: '♥', letter: 'h', color: 'red' } },
        { rank: { value: 5, symbol: '5' }, suit: { symbol: '♦', letter: 'd', color: 'red' } },
        { rank: { value: 8, symbol: '8' }, suit: { symbol: '♥', letter: 'h', color: 'red' } },
        { rank: { value: 11, symbol: 'J' }, suit: { symbol: '♣', letter: 'c', color: 'black' } },
      ],
      levels: {
        '1': { smallBlind: 10, bigBlind: 20 },
        '2': { smallBlind: 15, bigBlind: 30 },
        '3': { smallBlind: 25, bigBlind: 50 },
        '4': { smallBlind: 50, bigBlind: 100 },
        '5': { smallBlind: 75, bigBlind: 150 },
        '6': { smallBlind: 100, bigBlind: 200 },
        '7': { smallBlind: 200, bigBlind: 400 },
        '8': { smallBlind: 300, bigBlind: 600 },
        '9': { smallBlind: 400, bigBlind: 800 },
        '10': { smallBlind: 600, bigBlind: 1200 },
        '11': { smallBlind: 1000, bigBlind: 2000 },
        '12': { smallBlind: 1500, bigBlind: 3000 },
        '13': { smallBlind: 2000, bigBlind: 4000 },
        '14': { smallBlind: 3000, bigBlind: 6000 },
        '15': { smallBlind: 4000, bigBlind: 8000 },
        '16': { smallBlind: 6000, bigBlind: 12000 },
        '17': { smallBlind: 10000, bigBlind: 20000 },
        '18': { smallBlind: 15000, bigBlind: 30000 },
        '19': { smallBlind: 20000, bigBlind: 40000 },
      },
      players: [
        {
          index: 0,
          holeCards: [],
          hand: [],
          name: 'Scott Hellmuth',
          chips: 1500,
          chipsCurrentlyInvested: 0,
          id: '805e887f-d3b4-4c3e-afcc-662d2dde4bc3',
          hasFolded: false,
          isAllIn: false,
        },
        {
          index: 1,
          holeCards: [],
          hand: [],
          name: 'Scott Seiver',
          chips: 1500,
          chipsCurrentlyInvested: 0,
          id: '7447413c-74dc-4dc3-af7f-a953f3a95ae9',
          hasFolded: false,
          isAllIn: false,
        },
        {
          index: 2,
          holeCards: [],
          hand: [],
          name: 'Scott Selbst',
          chips: 1500,
          chipsCurrentlyInvested: 0,
          id: 'fdd9ac46-6a91-4731-9632-9c19d5cc06a6',
          hasFolded: false,
          isAllIn: false,
        },
        {
          index: 3,
          holeCards: [],
          hand: [],
          name: 'Vanessa Tran',
          chips: 1500,
          chipsCurrentlyInvested: 0,
          id: 'f4b822b8-5c9f-4506-8cf9-e40e76d495aa',
          hasFolded: false,
          isAllIn: false,
        },
        {
          index: 4,
          holeCards: [],
          hand: [],
          name: 'Jason Hellmuth',
          chips: 1490,
          chipsCurrentlyInvested: 10,
          id: '78ac026e-7cfc-4037-94bb-d3991e78ec4c',
          hasFolded: false,
          isAllIn: false,
        },
        {
          index: 5,
          holeCards: [],
          hand: [],
          name: 'Scott Boeree',
          chips: 1480,
          chipsCurrentlyInvested: 20,
          id: 'cf2fdfe9-8477-431a-8bb5-c145d44f3da0',
          hasFolded: false,
          isAllIn: false,
        },
      ],
      showdown: false,
      positions: { bb: 5, sb: 4, button: 3, cutoff: 2, mp: 1, utg: 0 },
      handHistory: [],
      handWinners: [],
      currentLevel: 1,
      currentStreet: 0,
      communityCards: {},
      nextPlayerToAct: 0,
      whatPlayerIsDealer: null,
      highestCurrentBettor: null,
    },
    { type: DEAL_CARDS_TO_PLAYERS },
  )
  expect(state).not.toBe({
    pot: 0,
    deck: [
      { rank: { value: 7, symbol: '7' }, suit: { symbol: '♠', letter: 's', color: 'black' } },
      { rank: { value: 4, symbol: '4' }, suit: { symbol: '♥', letter: 'h', color: 'red' } },
      { rank: { value: 8, symbol: '8' }, suit: { symbol: '♠', letter: 's', color: 'black' } },
      { rank: { value: 9, symbol: '9' }, suit: { symbol: '♠', letter: 's', color: 'black' } },
      { rank: { value: 13, symbol: 'K' }, suit: { symbol: '♥', letter: 'h', color: 'red' } },
      { rank: { value: 6, symbol: '6' }, suit: { symbol: '♠', letter: 's', color: 'black' } },
      { rank: { value: 5, symbol: '5' }, suit: { symbol: '♣', letter: 'c', color: 'black' } },
      { rank: { value: 13, symbol: 'K' }, suit: { symbol: '♦', letter: 'd', color: 'red' } },
      { rank: { value: 7, symbol: '7' }, suit: { symbol: '♣', letter: 'c', color: 'black' } },
      { rank: { value: 13, symbol: 'K' }, suit: { symbol: '♠', letter: 's', color: 'black' } },
      { rank: { value: 3, symbol: '3' }, suit: { symbol: '♦', letter: 'd', color: 'red' } },
      { rank: { value: 5, symbol: '5' }, suit: { symbol: '♥', letter: 'h', color: 'red' } },
      { rank: { value: 11, symbol: 'J' }, suit: { symbol: '♦', letter: 'd', color: 'red' } },
      { rank: { value: 4, symbol: '4' }, suit: { symbol: '♠', letter: 's', color: 'black' } },
      { rank: { value: 9, symbol: '9' }, suit: { symbol: '♣', letter: 'c', color: 'black' } },
      { rank: { value: 8, symbol: '8' }, suit: { symbol: '♣', letter: 'c', color: 'black' } },
      { rank: { value: 6, symbol: '6' }, suit: { symbol: '♦', letter: 'd', color: 'red' } },
      { rank: { value: 12, symbol: 'Q' }, suit: { symbol: '♠', letter: 's', color: 'black' } },
      { rank: { value: 2, symbol: '2' }, suit: { symbol: '♣', letter: 'c', color: 'black' } },
      { rank: { value: 3, symbol: '3' }, suit: { symbol: '♥', letter: 'h', color: 'red' } },
      { rank: { value: 6, symbol: '6' }, suit: { symbol: '♥', letter: 'h', color: 'red' } },
      { rank: { value: 2, symbol: '2' }, suit: { symbol: '♠', letter: 's', color: 'black' } },
      { rank: { value: 13, symbol: 'K' }, suit: { symbol: '♣', letter: 'c', color: 'black' } },
      { rank: { value: 7, symbol: '7' }, suit: { symbol: '♥', letter: 'h', color: 'red' } },
      { rank: { value: 14, symbol: 'A' }, suit: { symbol: '♥', letter: 'h', color: 'red' } },
      { rank: { value: 5, symbol: '5' }, suit: { symbol: '♦', letter: 'd', color: 'red' } },
      { rank: { value: 8, symbol: '8' }, suit: { symbol: '♥', letter: 'h', color: 'red' } },
      { rank: { value: 11, symbol: 'J' }, suit: { symbol: '♣', letter: 'c', color: 'black' } },
    ],
    levels: {
      '1': { smallBlind: 10, bigBlind: 20 },
      '2': { smallBlind: 15, bigBlind: 30 },
      '3': { smallBlind: 25, bigBlind: 50 },
      '4': { smallBlind: 50, bigBlind: 100 },
      '5': { smallBlind: 75, bigBlind: 150 },
      '6': { smallBlind: 100, bigBlind: 200 },
      '7': { smallBlind: 200, bigBlind: 400 },
      '8': { smallBlind: 300, bigBlind: 600 },
      '9': { smallBlind: 400, bigBlind: 800 },
      '10': { smallBlind: 600, bigBlind: 1200 },
      '11': { smallBlind: 1000, bigBlind: 2000 },
      '12': { smallBlind: 1500, bigBlind: 3000 },
      '13': { smallBlind: 2000, bigBlind: 4000 },
      '14': { smallBlind: 3000, bigBlind: 6000 },
      '15': { smallBlind: 4000, bigBlind: 8000 },
      '16': { smallBlind: 6000, bigBlind: 12000 },
      '17': { smallBlind: 10000, bigBlind: 20000 },
      '18': { smallBlind: 15000, bigBlind: 30000 },
      '19': { smallBlind: 20000, bigBlind: 40000 },
    },
    players: [
      {
        index: 0,
        holeCards: [
          { rank: { value: 12, symbol: 'Q' }, suit: { symbol: '♣', letter: 'c', color: 'black' } },
          { rank: { value: 8, symbol: '8' }, suit: { symbol: '♦', letter: 'd', color: 'red' } },
        ],
        hand: [],
        name: 'Scott Hellmuth',
        chips: 1500,
        chipsCurrentlyInvested: 0,
        id: '805e887f-d3b4-4c3e-afcc-662d2dde4bc3',
        hasFolded: false,
        isAllIn: false,
      },
      {
        index: 1,
        holeCards: [
          { rank: { value: 10, symbol: 'T' }, suit: { symbol: '♥', letter: 'h', color: 'red' } },
          { rank: { value: 10, symbol: 'T' }, suit: { symbol: '♦', letter: 'd', color: 'red' } },
        ],
        hand: [],
        name: 'Scott Seiver',
        chips: 1500,
        chipsCurrentlyInvested: 0,
        id: '7447413c-74dc-4dc3-af7f-a953f3a95ae9',
        hasFolded: false,
        isAllIn: false,
      },
      {
        index: 2,
        holeCards: [
          { rank: { value: 14, symbol: 'A' }, suit: { symbol: '♦', letter: 'd', color: 'red' } },
          { rank: { value: 4, symbol: '4' }, suit: { symbol: '♣', letter: 'c', color: 'black' } },
        ],
        hand: [],
        name: 'Scott Selbst',
        chips: 1500,
        chipsCurrentlyInvested: 0,
        id: 'fdd9ac46-6a91-4731-9632-9c19d5cc06a6',
        hasFolded: false,
        isAllIn: false,
      },
      {
        index: 3,
        holeCards: [
          { rank: { value: 10, symbol: 'T' }, suit: { symbol: '♠', letter: 's', color: 'black' } },
          { rank: { value: 11, symbol: 'J' }, suit: { symbol: '♥', letter: 'h', color: 'red' } },
        ],
        hand: [],
        name: 'Vanessa Tran',
        chips: 1500,
        chipsCurrentlyInvested: 0,
        id: 'f4b822b8-5c9f-4506-8cf9-e40e76d495aa',
        hasFolded: false,
        isAllIn: false,
      },
      {
        index: 4,
        holeCards: [
          { rank: { value: 3, symbol: '3' }, suit: { symbol: '♠', letter: 's', color: 'black' } },
          { rank: { value: 12, symbol: 'Q' }, suit: { symbol: '♦', letter: 'd', color: 'red' } },
        ],
        hand: [],
        name: 'Jason Hellmuth',
        chips: 1490,
        chipsCurrentlyInvested: 10,
        id: '78ac026e-7cfc-4037-94bb-d3991e78ec4c',
        hasFolded: false,
        isAllIn: false,
      },
      {
        index: 5,
        holeCards: [
          { rank: { value: 11, symbol: 'J' }, suit: { symbol: '♠', letter: 's', color: 'black' } },
          { rank: { value: 4, symbol: '4' }, suit: { symbol: '♦', letter: 'd', color: 'red' } },
        ],
        hand: [],
        name: 'Scott Boeree',
        chips: 1480,
        chipsCurrentlyInvested: 20,
        id: 'cf2fdfe9-8477-431a-8bb5-c145d44f3da0',
        hasFolded: false,
        isAllIn: false,
      },
    ],
    showdown: false,
    positions: { bb: 5, sb: 4, button: 3, cutoff: 2, mp: 1, utg: 0 },
    handHistory: [],
    handWinners: [],
    currentLevel: 1,
    currentStreet: 0,
    communityCards: {},
    nextPlayerToAct: 0,
    whatPlayerIsDealer: null,
    highestCurrentBettor: null,
  })
})
